name: GitHub Actions Core Features Secrets

# manual trigger
on:
  workflow_dispatch:
run-name: ${{ github.actor }} is learning GitHub Actions Core Features Secrets

# secrets can be stored in organization level, repository level, or environment level. They are encrypted and only exposed to selected actions and workflows. They are masked in logs to prevent accidental exposure.
# can only set secrets in the UI and can only be injected into actions.
jobs:
  stage-environment:
    runs-on: ubuntu-slim
    # specify environment to get environment-level secrets and variables injected. Can also be used for environment protection rules like required reviewers, wait timer, etc.
    environment: stage
    env:
      # Inject repository-level secret & variable into the shell
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.REPOSITORY_SECRET_EXAMPLE_1 }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.REPOSITORY_VARIABLE_EXAMPLE_1 }}

      # Inject environment-level items into the shell
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.ENV_SECRET_EXAMPLE_1 }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.ENV_ENVIRONMENT_EXAMPLE_1 }}
    steps:
      - name: Inspect values inside job
        run: |
          echo "Repo secret (masked):    $EXAMPLE_REPOSITORY_SECRET"
          echo "Repo variable:           $EXAMPLE_REPOSITORY_VARIABLE"
          echo "Env secret (masked):     $EXAMPLE_ENVIRONMENT_SECRET"
          echo "Env variable:            $EXAMPLE_ENVIRONMENT_VARIABLE"
  prod-environment:
    runs-on: ubuntu-slim
    environment: prod
    # need job1 to first pass data into outputs
    needs: stage-environment
    env:
      # Inject repository-level secret & variable into the shell
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.REPOSITORY_SECRET_EXAMPLE_1 }}
      EXAMPLE_REPOSITORY_VARIABLE: ${{ vars.REPOSITORY_VARIABLE_EXAMPLE_1 }}

      # Inject environment-level items into the shell
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.ENV_SECRET_EXAMPLE_1 }}
      EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.ENV_ENVIRONMENT_EXAMPLE_1 }}
    steps:
      - name: Inspect values inside job
        run: |
          echo "Repo secret (masked):    $EXAMPLE_REPOSITORY_SECRET"
          echo "Repo variable:           $EXAMPLE_REPOSITORY_VARIABLE"
          echo "Env secret (masked):     $EXAMPLE_ENVIRONMENT_SECRET"
          echo "Env variable:            $EXAMPLE_ENVIRONMENT_VARIABLE"
